### ISSUE TITLE
Tooltip Implementation onMousehover the Circle

### ISSUE THREAD

**Issue by ganapathi-egr** [shauns/react-d3-radar#15]
Hello,

Is that possible to implement the tooltip to display Label and values while mouse hover the circle...?

**Comment by shauns** [comment]
Hi @ganapathi-egr -- you can use the `onHover` prop to do this. Pass in a function and it will be called with the currently hovered value/label (or null if the user is no longer hovering over something). See https://github.com/shauns/react-d3-radar/blob/9947df7dce1519637aa04d97cfa723fea336fb85/src/Radar.js#L22 
It's then on you to decide what to do with that data and how you'd like to show it.
